### ISSUE TITLE
Raspberry PI: launch: program '' does not exist, with workaround

### ISSUE THREAD

**Issue by hbraasch** [SuessLabs/VsLinuxDebug#71]
## Description
When launching the debugger, I get the error message [launch: program '' does not exist]
A crude fix is shown below.

## Severity (1-5)
5 - Cannot debug

## Steps To Reproduce
Generate a stock .net console app
Setup the device specific data in the VSLinuxDebug Setup (IP addr, username, pwd)
Launch the debugger
See error message
To fix this, I had to make sure the setting [.Net executable] points to the full [dotnet] pathname. See below:

![image](https://github.com/SuessLabs/VsLinuxDebug/assets/7484186/38916896-4674-45e0-9c81-e13703bf29ae)

The arrow points to the path detail I needed to add for my specific installation.
I tried this also: [export DOTNET_ROOT=/usr/lib/dotnet] but that did not solve the problem.

## Expected Behavior
Hit breakpoint.

## Screenshots
Not applicable

## Linux Distribution:
* **OS:** [Debian]

**Comment by DamianSuess** [comment]
Thank you @hbraasch for reporting this issue. During the installation, the system is configured to use the default DotNet command that does not require the full installation path. Since there are so many distributions, it's difficult to test them all and I really appreciate you bringing this to light.  For my tests, I usually stick with Ubuntu 20.04, 22.04, and sometimes Kali.

* Are you able to execute `dotnet` command by itself from the terminal?  (i.e., `dotnet --list-sdks`)?
* Which version of the Debian distribution are you using?

https://github.com/SuessLabs/VsLinuxDebug/blob/cb84f6aaae9217525762b5dc96b60381a3dee9d8/src/VsLinuxDebugger/OptionsPages/OptionsPage.DotNet.cs#L27

https://github.com/SuessLabs/VsLinuxDebug/blob/cb84f6aaae9217525762b5dc96b60381a3dee9d8/src/VsLinuxDebugger/Commands.Impl.cs#L175

**Comment by esonhon** [comment]
Same here, my remote configuration is:  Ubuntu 20.0.4 LTS for Arm64.
Point the .Net executable to full path solved this problem.
