### ISSUE TITLE
Should "Build and Deploy" start the app automatically on my Linux target machine?

### ISSUE THREAD

**Issue by jorgedevs** [SuessLabs/VsLinuxDebug#72]
Not sure how else I could reach out to post a question but when I try both **Build and Deploy**, and **Build, Deploy and Debug**, am I expecting that the app will run automatically on my target linux machine? because it doesnt, I have to go to where the project was uploaded and do `dotnet run` to run it. 

Would be cool if it runs by itself like I would run a Windows app, Android app on a phone, etc.

Thanks in advance, this tool is still super helpful to me. Nice work!

**Comment by DamianSuess** [comment]
Thank you, @jorgedevs, for reaching out. This feature is still in the testing phase as I've found it doesn't always work from environment-to-environment. Looking to improve the system to make it better.

What environment are you deploying to?  (_Linux Distro, version, .NET version, and is it GUI or CLI_)

In the meantime, are you able to manually attach to the debugger via Visual Studio after deploying it?

https://github.com/SuessLabs/VsLinuxDebug/wiki/Debugging-Manually

See also, [#49 Launch GUI after Deploying Package](https://github.com/SuessLabs/VsLinuxDebug/issues/49)

**Comment by jorgedevs** [comment]
Sure, I'm working on an Avalonia 11 application and my setup is:

Dev Machine:
Windows 11 (Latest stable version)
Visual Studio 2022 (17.7.4)
.NET 7.0.401

Target machine:
[SeeedStudio reTerminal](https://www.seeedstudio.com/ReTerminal-with-CM4-p-4904.html)
Linux Debian (11)
.NET 7.0.305
GUI

I am able to attach the debugger, but dont need it at the moment, so I just use your extension to build and transfer the project to the target device, then I vnc in to run `dotnet <myapp>,dll` to run it.

**Comment by DamianSuess** [comment]
@jorgedevs,
By the way, to directly answer the issue's title question, "**Build and Deploy**" only builds the application and then deploys it to the target machine. The feature you're ideally referring to is, "_Build, Deploy, and Debug (experimental)_" which is still getting the kinks worked out. At the moment, this feature is temperamental due to individual environments. Getting feedback from members like yourself really helps.

![Build-Deploy-Execute](https://github.com/SuessLabs/VsLinuxDebug/assets/1216684/7d1a3d8c-df8b-4926-8079-da041c6f2d9f)

In the meantime, I hope you keep having success with this extension and it helps speed up your deployments for testing. 👍
